//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFramework.Engine {
    
    // AssetBundle资源名称常量，自动生成，请勿修改
    public partial class AssetsName {
        public class Chapter01Unity {
            public const string ASSET_BUNDLE_NAME = "chapter_01-unity";
            public const string CHAPTER_01 = "chapter_01";
        }
        public class Chapter02Unity {
            public const string ASSET_BUNDLE_NAME = "chapter_02-unity";
            public const string CHAPTER_02 = "chapter_02";
        }
        public class CodePng {
            public const string ASSET_BUNDLE_NAME = "code-png";
            public const string CODE = "code";
        }
        public class LiliyPrefab {
            public const string ASSET_BUNDLE_NAME = "liliy-prefab";
            public const string LILIY = "liliy";
        }
        public class MalongPrefab {
            public const string ASSET_BUNDLE_NAME = "malong-prefab";
            public const string MALONG = "malong";
        }
        public class Pack1 {
            public const string ASSET_BUNDLE_NAME = "pack1";
            public const string ASSETOBJ = "assetobj";
        }
        public class Pack2 {
            public const string ASSET_BUNDLE_NAME = "pack2";
            public const string ASSETOBJ = "assetobj";
        }
        public class SceneUnity {
            public const string ASSET_BUNDLE_NAME = "scene-unity";
            public const string BASICUSAGETEST = "basicusagetest";
        }
        public class SpriteatlasvSpriteatlasv2 {
            public const string ASSET_BUNDLE_NAME = "spriteatlasv-spriteatlasv2";
            public const string SPRITEATLASV = "spriteatlasv";
        }
    }
}
